//! Scatter logic — generate instance transforms from terrain surface data.
//!
//! Ports the engine-agnostic half of `terrain/instancing/voxel_instance_generator.{h,cpp}`.
//! A generator receives block surface positions + normals and produces
//! per-instance transforms (position, rotation, scale).

use crate::math::Vector3f;

/// Configuration for scatter generation.
#[derive(Debug, Clone)]
pub struct ScatterConfig {
    /// Random seed.
    pub seed: u32,
    /// Maximum instances per block (safety cap).
    pub max_per_block: u32,
}

impl Default for ScatterConfig {
    fn default() -> Self {
        Self {
            seed: 0,
            max_per_block: 1000,
        }
    }
}

/// Per-instance data generated by the scatter pass. One per placed instance.
#[derive(Debug, Clone, Copy)]
pub struct BlockInstanceData {
    /// World-space position.
    pub position: Vector3f,
    /// Rotation as a quaternion (xyzw).
    pub rotation: [f32; 4],
    /// Uniform scale.
    pub scale: f32,
    /// Which library item this instance belongs to.
    pub item_index: u32,
}

/// A scatter generator: produces instances from terrain surface data.
pub trait InstanceGenerator: Send + Sync {
    /// Generate instances for a block.
    ///
    /// `surface_positions` and `surface_normals` are parallel arrays of
    /// terrain surface points in world space. `item_index` selects which
    /// library item to scatter.
    fn generate(
        &self,
        surface_positions: &[Vector3f],
        surface_normals: &[Vector3f],
        item_index: u32,
        config: &ScatterConfig,
    ) -> Vec<BlockInstanceData>;
}

/// A simple random scatter generator. Places instances at surface positions
/// with random yaw/scale based on the library item's density.
pub struct RandomScatterGenerator {
    pub density: f32,
    pub min_scale: f32,
    pub max_scale: f32,
    pub snap_to_normal: bool,
}

impl InstanceGenerator for RandomScatterGenerator {
    fn generate(
        &self,
        surface_positions: &[Vector3f],
        surface_normals: &[Vector3f],
        item_index: u32,
        config: &ScatterConfig,
    ) -> Vec<BlockInstanceData> {
        let mut rng = SimpleRng::new(config.seed.wrapping_add(item_index));
        let mut result = Vec::new();
        let max = config.max_per_block as usize;

        for (i, pos) in surface_positions.iter().enumerate() {
            if result.len() >= max {
                break;
            }
            // Density check: each surface point has a `density` probability.
            if rng.next_f32() > self.density {
                continue;
            }
            let normal = surface_normals
                .get(i)
                .copied()
                .unwrap_or(Vector3f::new(0.0, 1.0, 0.0));
            let scale = self.min_scale + rng.next_f32() * (self.max_scale - self.min_scale);
            let yaw = rng.next_f32() * std::f32::consts::TAU;

            let rotation = if self.snap_to_normal {
                look_at_yaw(normal, yaw)
            } else {
                quat_yaw(yaw)
            };

            result.push(BlockInstanceData {
                position: *pos,
                rotation,
                scale,
                item_index,
            });
        }
        result
    }
}

/// Simple xorshift PRNG for deterministic scatter.
struct SimpleRng {
    state: u32,
}

impl SimpleRng {
    fn new(seed: u32) -> Self {
        Self {
            state: if seed == 0 { 1 } else { seed },
        }
    }

    fn next_u32(&mut self) -> u32 {
        self.state ^= self.state << 13;
        self.state ^= self.state >> 17;
        self.state ^= self.state << 5;
        self.state
    }

    fn next_f32(&mut self) -> f32 {
        self.next_u32() as f32 / u32::MAX as f32
    }
}

/// Quaternion for yaw rotation around Y.
fn quat_yaw(yaw: f32) -> [f32; 4] {
    let half = yaw * 0.5;
    [0.0, half.sin(), 0.0, half.cos()]
}

/// Align to surface normal + apply yaw around the normal axis.
fn look_at_yaw(normal: Vector3f, yaw: f32) -> [f32; 4] {
    // Simplified: use normal as up, yaw around Y.
    // Full implementation would use a proper look-at quaternion.
    let n = normalize(normal);
    let right = cross(Vector3f::new(0.0, 0.0, 1.0), n);
    let up = cross(n, right);
    // Build rotation matrix → quaternion (simplified to yaw + tilt).
    let yaw_q = quat_yaw(yaw);
    // Blend with normal alignment (basic version).
    let tilt_q = quat_from_vectors(Vector3f::new(0.0, 1.0, 0.0), up);
    quat_mul(&tilt_q, &yaw_q)
}

fn normalize(v: Vector3f) -> Vector3f {
    let len = (v.x * v.x + v.y * v.y + v.z * v.z).sqrt();
    if len > 1e-10 {
        Vector3f::new(v.x / len, v.y / len, v.z / len)
    } else {
        Vector3f::new(0.0, 1.0, 0.0)
    }
}

fn cross(a: Vector3f, b: Vector3f) -> Vector3f {
    Vector3f::new(
        a.y * b.z - a.z * b.y,
        a.z * b.x - a.x * b.z,
        a.x * b.y - a.y * b.x,
    )
}

fn quat_from_vectors(from: Vector3f, to: Vector3f) -> [f32; 4] {
    let dot = from.x * to.x + from.y * to.y + from.z * to.z;
    if dot > 0.9999 {
        [0.0, 0.0, 0.0, 1.0] // identity
    } else {
        let axis = cross(from, to);
        let s = ((2.0 * (1.0 + dot)).max(0.0)).sqrt();
        [axis.x / s, axis.y / s, axis.z / s, s * 0.5]
    }
}

fn quat_mul(a: &[f32; 4], b: &[f32; 4]) -> [f32; 4] {
    [
        a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1],
        a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0],
        a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3],
        a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2],
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn random_scatter_produces_instances() {
        let gen = RandomScatterGenerator {
            density: 1.0, // Accept all points
            min_scale: 0.5,
            max_scale: 1.5,
            snap_to_normal: true,
        };
        let positions = vec![
            Vector3f::new(0.0, 10.0, 0.0),
            Vector3f::new(5.0, 11.0, 3.0),
            Vector3f::new(-2.0, 9.0, 7.0),
        ];
        let normals = vec![Vector3f::new(0.0, 1.0, 0.0); 3];
        let config = ScatterConfig::default();
        let result = gen.generate(&positions, &normals, 0, &config);
        assert_eq!(result.len(), 3, "density=1.0 should accept all 3 points");
        assert!(result[0].scale >= 0.5 && result[0].scale <= 1.5);
        assert_eq!(result[0].item_index, 0);
    }

    #[test]
    fn random_scatter_respects_max_per_block() {
        let gen = RandomScatterGenerator {
            density: 1.0,
            min_scale: 1.0,
            max_scale: 1.0,
            snap_to_normal: false,
        };
        let positions: Vec<_> = (0..100)
            .map(|i| Vector3f::new(i as f32, 0.0, 0.0))
            .collect();
        let normals = vec![Vector3f::new(0.0, 1.0, 0.0); 100];
        let config = ScatterConfig {
            max_per_block: 10,
            ..Default::default()
        };
        let result = gen.generate(&positions, &normals, 0, &config);
        assert_eq!(result.len(), 10, "should cap at max_per_block");
    }

    #[test]
    fn scatter_is_deterministic_with_seed() {
        let gen = RandomScatterGenerator {
            density: 0.5,
            min_scale: 0.5,
            max_scale: 1.5,
            snap_to_normal: true,
        };
        let positions: Vec<_> = (0..50).map(|i| Vector3f::new(i as f32, 0.0, 0.0)).collect();
        let normals = vec![Vector3f::new(0.0, 1.0, 0.0); 50];
        let config = ScatterConfig {
            seed: 42,
            max_per_block: 100,
        };
        let r1 = gen.generate(&positions, &normals, 0, &config);
        let r2 = gen.generate(&positions, &normals, 0, &config);
        assert_eq!(r1.len(), r2.len(), "same seed should produce same count");
        for (a, b) in r1.iter().zip(r2.iter()) {
            assert_eq!(a.position.x, b.position.x, "positions should match");
        }
    }
}
